
CONTAINER_NAME="tp4-app"
IMAGE_NAME="im-tp4"
NETWORK_NAME="net-tp4"
HOST_PORT=5000
CONTAINER_PORT=5000

docker run -d \
  --name $CONTAINER_NAME \
  --network $NETWORK_NAME \
  -p $HOST_PORT:$CONTAINER_PORT \
  $IMAGE_NAME
